### ISSUE TITLE
How about use density grid to accelerate the raymarching?

### ISSUE THREAD

**Issue by Saoyu99** [SuLvXiangXin/zipnerf-pytorch#14]
I'm thinking to replace the proposal network with the instant-ngp's density grid. 
Do you think this will be effective?

**Comment by SuLvXiangXin** [comment]
@Saoyu99 Yeah, I think this can accelerate the convergence, but might also harm the PSNR.

**Comment by SuLvXiangXin** [comment]
Maybe there is a way to benifit from both sides. You can have a try~
