### ISSUE TITLE
local_colmap_and_resize.sh does not create transform.json

### ISSUE THREAD

**Issue by ichsan2895** [SuLvXiangXin/zipnerf-pytorch#16]
Syntax that I ran:
```
$ git clone https://github.com/SuLvXiangXin/zipnerf-pytorch

$ cd zipnerf-pytorch

$ pip install -r requirement.txt

#  I create a folder called images which contains lego bulldozer raw images in LEGO folder. 
$ bash scripts/local_colmap_and_resize.sh ./LEGO

# I dont have DDP and I ran without accelerate
$ CUDA_VISIBLE_DEVICES=0 python3 train.py \
    --gin_configs=configs/360.gin \
    --gin_bindings="Config.data_dir = 'LEGO'" \
    --gin_bindings="Config.exp_name = 'LEGO'" \
      --gin_bindings="Config.factor = 0"

FileNotFoundError: [Errno 2] No such file or directory: 'LEGO/transforms.json'
```

**Comment by SuLvXiangXin** [comment]
@ichsan2895 please check whether you have `sparse/0/` in your folder.

**Comment by ichsan2895** [comment]
> @ichsan2895 please check whether you have `sparse/0/` in your folder.

![image](https://user-images.githubusercontent.com/60387342/237019703-b0cc724f-4670-445a-af21-9cea16284afb.png)
Sorry, the `transform.json` is not available in there

**Comment by SuLvXiangXin** [comment]
![image](https://user-images.githubusercontent.com/83005605/237055613-f4bf9bca-b3f9-42aa-a361-a81d7e1a9385.png)
@ichsan2895 You can see that `transform.json` is only needed if you don't have `sparse/0/` in your folder.
