### ISSUE TITLE
about llff_raw.gin

### ISSUE THREAD

**Issue by Miner-AI** [SuLvXiangXin/zipnerf-pytorch#18]
hi! I have a question about configs.llff_raw.gin. 
This config file may missing the definition about Model.raydist_fn, I don't know how to choose this parameters.
Hope for your reply!

**Comment by SuLvXiangXin** [comment]
please refer to [this](https://github.com/SuLvXiangXin/multinerf-pytorch/issues/1#issuecomment-1541990423)
