### ISSUE TITLE
Fail to run train_blender.sh

### ISSUE THREAD

**Issue by Daiqy** [SuLvXiangXin/zipnerf-pytorch#24]
Hi! I try to run train_blender.sh but it dosen't work. I modify the script and use GPU id 7 here.
![image](https://github.com/SuLvXiangXin/zipnerf-pytorch/assets/26495036/3334575f-5ab2-436e-b1e8-172287b69e12)

**Comment by SuLvXiangXin** [comment]
@Daiqy Hi, can you try the latest version? If there is still something wrong, please give the entire error message, or the logging in the log_train.txt.

**Comment by Daiqy** [comment]
I solved the problem after recreating the conda environment. Thank you!
