### ISSUE TITLE
 space = ((grid_max - grid_min).prod() / config.mesh_voxels) ** (1 / 3) AttributeError: 'Config' object has no attribute 'mesh_voxels'

### ISSUE THREAD

**Issue by pokameng** [SuLvXiangXin/zipnerf-pytorch#26]
@SuLvXiangXin  
space = ((grid_max - grid_min).prod() / config.mesh_voxels) ** (1 / 3)
AttributeError: 'Config' object has no attribute 'mesh_voxels'

`accelerate launch extract_mod.py \
    --gin_configs=configs/360.gin \
    --gin_bindings="Config.data_dir = '${DATA_DIR}'" \
    --gin_bindings="Config.exp_name = '${EXP_NAME}'" \
    --gin_bindings="Config.factor = 4" \
    --gin_bindings="Config.mesh_radius = 1"  \
    --gin_bindings="Config.isosurface_threshold = 20"  \
    --gin_bindings="Config.mesh_resolution = 1024"  \
    --gin_bindings="Config.vertex_color = True"  `

**Comment by SuLvXiangXin** [comment]
@pokameng Please check out the latest commit
