### ISSUE TITLE
Wierd render results

### ISSUE THREAD

**Issue by marisancans** [SuLvXiangXin/zipnerf-pytorch#3]
Trying to reproduce the results but they are really wierd.
GPU: RTX 3090 24GB
Commit: 1146e86
Notice that I set batch size to 2, is that okay?

Script executed:
```
#!/bin/bash

SCENE=bicycle
EXPERIMENT=360_v2/"$SCENE"
DATA_ROOT=/SSD_DISK/datasets/360_v2
DATA_DIR=./data/bicycle



CUDA_VISIBLE_DEVICES=0 accelerate launch render.py \
  --gin_configs=configs/360.gin \
  --gin_bindings="Config.data_dir = '${DATA_DIR}'" \
  --gin_bindings="Config.exp_name = '${EXPERIMENT}'" \
  --gin_bindings="Config.batch_size = 2" \
  --gin_bindings="Config.render_path = True" \
  --gin_bindings="Config.render_path_frames = 120" \
  --gin_bindings="Config.render_video_fps = 60" \
  --gin_bindings="Config.factor = 4"

```

No additional changes were made in the scripts.
In the output folder exp/360_v2/bicycle/render/path_renders_step_0 I have images like this:
![image](https://user-images.githubusercontent.com/16538903/234306973-7815d26a-21b9-4c4c-9889-656b9f90a9e2.png)

I see that it created a folder named step_0, does this mean I have to render again with multiple steps?
distance_mean*.tiff and acc*.tiff images are black.
Generated video cant be played on vlc for some reason, but generated thumbnails indicate that there is nothing good there too

![image](https://user-images.githubusercontent.com/16538903/234307514-36999346-19fe-4947-b9af-2dbab0caf77a.png)

Edit: I removed the batch size argument and will try to render again, maybe thats the problem. Im not sure that it even does anything because I dont see any changes in GPU memory. Maybe there is some sort of accumulation

**Comment by liyaoshun** [comment]
Attempt to set batch_size to 8192 or greater

**Comment by SuLvXiangXin** [comment]
By the way, I recommand you to run `accelerate config` first, you can choose what device and how many devices to use. After that you don't need to use`CUDA_VISIBLE_DEVICES=0`

**Comment by marisancans** [comment]
Apologies, I didn't know you had to train it before rendering, makes sense.
Thank you for the fast response.
I managed to run the training code.

Something to note, when doing $pip install torch-scatter, it by default installs a cpu version, you have to install it like this:
`pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+${CUDA}.html`
This is if someone has an error of something like "Was not built with CUDA support"

**Comment by SuLvXiangXin** [comment]
Thanks for the reminder
