### ISSUE TITLE
About zipnerf combine with numerical gradients on grid-hash enconding

### ISSUE THREAD

**Issue by atztao** [SuLvXiangXin/zipnerf-pytorch#31]

**Comment by tianxiaguixin002** [comment]
Neuralangelo not publish their source code, similar code maybe founded in sdfstudio. like neus-facto

**Comment by atztao** [comment]
> Neuralangelo not publish their source code, similar code maybe founded in sdfstudio. like neus-facto

maybe we can used some convlution operation get similar smooth effect to replace the numerical gradients in the loss.

**Comment by tianxiaguixin002** [comment]
sdfstudio will implement Neuralangelo, just wait.

**Comment by atztao** [comment]
> sdfstudio will implement Neuralangelo, just wait.

效果怎么样

**Comment by atztao** [comment]
@SuLvXiangXin Can merge the numerical gradient in this code with https://github.com/bennyguo/instant-nsr-pl/issues/84 and https://github.com/bennyguo/instant-nsr-pl/issues/83
