### ISSUE TITLE
'NerfMLP' object has no attribute 'register_module'

### ISSUE THREAD

**Issue by ldzhuang** [SuLvXiangXin/zipnerf-pytorch#32]
![889BE26F-5148-4ef3-A99D-D5EFF0A1DF6D](https://github.com/SuLvXiangXin/zipnerf-pytorch/assets/64113233/079c559a-3bb3-4213-b4e0-435c7a973c0c)

**Comment by SuLvXiangXin** [comment]
@ldzhuang Maybe update your Pytorch version?

**Comment by ldzhuang** [comment]
thank you very much
