### ISSUE TITLE
ERROR: Failed to parse options - unrecognised option '--Mapper.ba_global_function_tolerance=0.000001'.

### ISSUE THREAD

**Issue by ldzhuang** [SuLvXiangXin/zipnerf-pytorch#36]
![B0BE22F8-0E31-4fea-93DC-EE31ED2A1761](https://github.com/SuLvXiangXin/zipnerf-pytorch/assets/64113233/9b2bc50e-c134-4bad-8832-59ed9ff8a70c)

**Comment by SuLvXiangXin** [comment]
@ldzhuang Maybe results from your colmap version. You can try to just comment out this line.

**Comment by ldzhuang** [comment]
thank you so much,It's a great job
