### ISSUE TITLE
About implementation of Affine GLO

### ISSUE THREAD

**Issue by sangminkim-99** [SuLvXiangXin/zipnerf-pytorch#4]
Hi there, @SuLvXiangXin!

First of all, I wanted to thank you for sharing your implementation. I appreciate the work you've done.

I did notice some floaters in the demo video and wanted to bring it to your attention. I believe that the issue may be related to GLO.

After reading through Appendix A of the paper, I noticed that the authors did not concatenate GLO at the bottleneck vector, as you did in [this part](https://github.com/SuLvXiangXin/zipnerf-pytorch/blob/b9a05b316811baaaaec24290ef51466692957897/internal/models.py#L563). Instead, they used an mlp to map GLO to affine transform vectors.

I hope this information is helpful in improving the quality of your implementation. Thank you so much for your hard work and dedication.

Best regards,
Sang Min Kim.

**Comment by SuLvXiangXin** [comment]
Thanks for reminder, I have implemented it just now, you can find it in the lastest commit. And a more comprehensive experiment will be conducted.

**Comment by sangminkim-99** [comment]
Thank you!
