### ISSUE TITLE
GridEncoder

### ISSUE THREAD

**Issue by Ilyabasharov** [SuLvXiangXin/zipnerf-pytorch#42]
Hi! Why do you use custom implementation grid encoder and not [tinycudann](https://github.com/NVlabs/tiny-cuda-nn) HashGrid? what are the differences?
Thanks for your answers.

**Comment by SuLvXiangXin** [comment]
@Ilyabasharov The custom implementation `torch-ngp` is more flexible and easier to modify.

**Comment by Ilyabasharov** [comment]
Thanks!
