### ISSUE TITLE
gradient scaling?

### ISSUE THREAD

**Issue by zhiwenfan** [SuLvXiangXin/zipnerf-pytorch#43]
Hi, thanks for the great contribution for this community! I was wondering if you are intend to implement gradient scaling (https://gradient-scaling.github.io/) for solving near-camera floaters? Thanks.

**Comment by SuLvXiangXin** [comment]
@zhiwenfan Thanks, it's available now.  Just add `--gin_bindings="Config.gradient_scaling = True"`  to turn it on. The near plane is not set to 0, as I'm not sure how to modify the power transformation.
