### ISSUE TITLE
Friendly ask for pretrained weights

### ISSUE THREAD

**Issue by AAAeray** [SuLvXiangXin/zipnerf-pytorch#51]
Hi,
Thanks for your great work! Is that convenient for you to share the pretrained weights that have been shown in the readme file? I want to extract the depth maps of those scences in my work. I have train and test it with the bicycle datasets, which is awesome!  But I only have a single-GPU computer, it will takes me a lot of time to train for all scences.
Still thanks you if it's not convenient.

**Comment by SuLvXiangXin** [comment]
OK, I'll share it tomorow.

**Comment by AAAeray** [comment]
Thanks a looot!

**Comment by SuLvXiangXin** [comment]
@AAAeray Pretrained weights:https://drive.google.com/drive/folders/1W1jFa519m7Ye9Pcz5N_30TMPM-7KTTBc?usp=sharing

**Comment by SuLvXiangXin** [comment]
Pretrained weights of blender are still uploading. Please told me if there is anything missing.

**Comment by AAAeray** [comment]
Thanks, I really appreciate for your help.
