### ISSUE TITLE
Biased color at early stage of training / blurry foreground when fullly trained

### ISSUE THREAD

**Issue by jingyibo123** [SuLvXiangXin/zipnerf-pytorch#58]
Kudos for the work!

When training the `360 dataset` with the default `360_glo` config using 4GPUs, I noticed two problems with the result:

1. During early stages of the training, the test image of foreground object shows weird color,  For example the bicycle scene (I can't upload images...): The frame of the bicycle is went from red to gray to blue to white (still a bit blue)

2. When fully trained, the objects (chair and bicycle) are still blurry compared with the background, and both the chair and bicycle have a blue color shade..d

Could it be the view-dependent MLP?
Thanks in advance!

**Comment by SuLvXiangXin** [comment]
@jingyibo123 I think this may results from the `glo_vec` proposed in paper which is used to scale and bias the `bottleneck` feature. If you get a weird result, you can try the default `360.gin` instead.

**Comment by jingyibo123** [comment]
Indeed, thanks!
