### ISSUE TITLE
 No such file or directory: '/bicycle/transforms.json'

### ISSUE THREAD

**Issue by LissetheGarcia** [SuLvXiangXin/zipnerf-pytorch#6]
!pwd
os.chdir('/content/zipnerf-pytorch/')
!pwd

!accelerate config default

Where your data is 
!DATA_DIR=data/bicycle
!EXP_NAME=/bicycle

Experiment will be conducted under "exp/${EXP_NAME}" folder
"--gin_configs=configs/360.gin" can be seen as a default config 
and you can add specific config useing --gin_bindings="..." 
!accelerate launch train.py \
    --gin_configs=configs/360.gin \
    --gin_bindings="Config.data_dir = '${DATA_DIR}'" \
    --gin_bindings="Config.exp_name = '${EXP_NAME}'" \
    --gin_bindings="Config.factor = 0"

I get this error:

Found no checkpoint files in exp/ with prefix checkpoint_

 No such file or directory: '/bicycle/transforms.json'

**Comment by SuLvXiangXin** [comment]
Please change your EXP_NAME to `./bicycle` while `/bicycle` is an absolute path. Also please check your data and DATA_DIR. "No such file or directory: '/bicycle/transforms.json'" means that it can't find data in `/bicycle/` directory.

**Comment by LissetheGarcia** [comment]
Thanks, I have tried it out, but I continue having one of the  two errors:

"Found no checkpoint files in exp/ with prefix checkpoint_"

**Comment by SuLvXiangXin** [comment]
@LissetheGarcia This is not an error, just a warning that means you are training from srcatch.
