### ISSUE TITLE
!accelerate config 

### ISSUE THREAD

**Issue by LissetheGarcia** [SuLvXiangXin/zipnerf-pytorch#7]
![image](https://user-images.githubusercontent.com/109912046/235031323-cf8b5d29-10dc-4f36-b1c7-035dfc85bc29.png)
I am running in a colab notebook, how it is supposed, I should put into this section?

Hugging Face is not really clear about this, and colab does not accept "enter"

https://huggingface.co/docs/accelerate/package_reference/cli

I tryed:
"shift" + "enter"
"ctrl" + "enter"
and others, but nothing

**Comment by SuLvXiangXin** [comment]
You can run `accelerate launch ....` directly while do no configure `accelerate config`. `accelerate config` is used to configure for multiprocess running, mixed precision, etc. If you do not config it, it will run by default. Besides you can also configure by e.g. `accelerate launch --multi_gpu --mixed_precision=fp16 --num_processes=2 ....`, which you can find  [here](https://huggingface.co/docs/accelerate/basic_tutorials/launch).

**Comment by LissetheGarcia** [comment]
Thanks :), I got it.
